# Generated by Django 3.2.12 on 2022-04-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('contact_at', models.DateField()),
            ],
        ),
    ]
